# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0


jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - azure-cli/install
workflows:
  example-workflow:
    jobs:
      - example-job